### ISSUE TITLE
Why  only red is output

### ISSUE THREAD

**Issue by xcma** [halaxa/json-machine#100]
//fruitsArray.json
{
    "results": [
        {
            "name": "apple",
            "color": "red"
        },
        {
            "name": "pear",
            "color": "yellow"
        }
    ]
}

//code
$fruits = Items::fromFile('fruitsArray.json', ['pointer' => '/results/-/color']);

foreach ($fruits as $key => $value) {
    var_dump($value);
}

**Comment by xcma** [comment]
$fruits = Items::fromString('{"results":[{"color":"red"},{"color":"yellow"}]}', ['pointer' => '/results/-/color']);
        foreach ($fruits as $key => $value) {
            var_dump($value);
        }
        
        output "red" and  "yellow"

**Comment by xcma** [comment]
$fruits = Items::fromString('{"results":[{"name":"apple","color":"red"},{"name":"pear","color":"yellow"}]}', ['pointer' => '/results/-/color']);
        foreach ($fruits as $key => $value) {
            var_dump($value);
        }
        
       only output  "red"

**Comment by halaxa** [comment]
Thanks, I'll try to get to it ASAP.

**Comment by halaxa** [comment]
Good job with hitting the #💯btw 😂👍

**Comment by halaxa** [comment]
Hi, this test b13aeacee843e1406a306cc01df0425ae7abe7b4 shows it works. There was probably a problem with your code. Closing fow now. Feel free to reopen.
