### ISSUE TITLE
Feature Request: Parse directly into a object of a PHP class

### ISSUE THREAD

**Issue by tacman** [halaxa/json-machine#113]
What a cool library, thanks for releasing it!  At first I thought I'd use it just when the JSON didn't fit in memory, but now I'm looking at replacing all of my $data = json_decode(file_get_contents('data.json')) with this.

I've used https://sabre.io/xml/reading/ to parse large XML files.  I quite like the way I can define a php class and the parser will objects of that class (see the Custom element parsers section).  I'm wondering if that's someone you've considered, a custom decoder based on a PHP class.

```php
class Fruits 
{
    /** @var array<Fruit> $fruits */
    public array $fruits=[];
}

class Fruit
{  
     public string $name;
     public string $color;
    /** @var array<Harvest> $harvests */
     public array $harvests=[];
   
     public function getHarvests(): iterator
     {
          return $this->harvests;
     }
}

class Harvest
{
    var int $year;
    var int $poundsCollected;
}
```

Then parse into directly into the class objects

```php
$fruits = Items::fromFile('fruits.json', Fruits::class);

foreach ($fruits as $fruit) {
    assert($fruit::class == Fruit::class);
    foreach ($fruit->getHarvests() as $harvest) {
         assert($harvest::class == Harvest::class);
         dd($harvest->year);
   }
}
```

I've found this particularly powerful when parsing nested documents, as they'd come back as a completely populated as class objects.  

Thanks for your consideration.

**Comment by halaxa** [comment]
Hello and thank you for your suggestion and positive feedback on the library!

While your proposal for a custom decoder based on PHP classes is interesting, I currently don't plan to implement this feature directly into the library. I aim to keep the library focused on its core purpose - efficient reading and processing of large JSON files.

**Comment by tacman** [comment]
Any suggestions on how to implement it?  Symfony now has several tools for mapping data to objects, mostly the serializer component but also the PropertyAccessor component and MapPayloadRequest (https://symfony.com/doc/current/controller.html#mapping-request-payload)

So I'm guessing there's a way in your parser to listen for a particular node/subtree and do the mapping there.  Or maybe simply iterate through the nodes and deserialize the objects.  Hmm.

**Comment by halaxa** [comment]
In such cases, I personally like to use no mapper libraries, but to simply create your own objects with accessor methods. Then pass the data (array, object) into the constructor. To me, it has many benefits that outweigh possible downsides.

**Comment by tacman** [comment]
Thanks.  I was hoping to automate it a bit more with a library.  The serializer will probably work.

**Comment by halaxa** [comment]
Sure. Each to their own ;)
