### ISSUE TITLE
Creating an array from items at the same level

### ISSUE THREAD

**Issue by Matt2012** [halaxa/json-machine#17]
In my use case I want to get all results for a certain nth depth.
```
 "rest": [
    {
      "mode": "server",
      "resource": [
          "type": "AllergyIntolerance",
...]
      "resource": [
          "type": "MedicationStatement",
...]
```
 So I want to return all resource types:
i.e.
`["AllergyIntolerance","MedicationStatement"]`

Is that possible?

**Comment by halaxa** [comment]
Hi it is probably possible, but the structure of the json is not clear to me from this example. Could you please provide minimal, full valid json as an example first? Thank you.

**Comment by halaxa** [comment]
Ping @Matt2012

**Comment by halaxa** [comment]
Closing for now, let me know if this problem becomes relevant again.
