### ISSUE TITLE
Library should not be tied to specific data reading protocols

### ISSUE THREAD

**Issue by Bilge** [halaxa/json-machine#18]
This library should not have either of the methods: `fromFile()` nor `fromStream()`. Perhaps these could be kept around as a convenience, but a pure implementation should not have methods that deal with reading files or streams, because insodoing, the library only supports files and streams. If I wanted to use this library with a general purpose async framework like Amp or React, I can't, because it doesn't explicitly support them. A well designed implementation would not tie itself to particular data protocols, instead just accepting incomplete JSON fragments from a string buffer, like [Duct](https://github.com/icecave/duct).

**Comment by halaxa** [comment]
Luckily Json machine is not tied to any data protocol. Those methods **are** just convenient methods. If you look inside any of the `from*` methods, you'll see how its done. Core implementation is based on iterables which is consumed by foreach internally. You can pass it any iterable that produces bytes of json string. Example:

```php
$jsonDocumentChunks = ["{", "'one': 'two'", "}"]; // or any iterable, be it array, Iterator or Generator
$iterator = JsonMachine($jsonDocumentChunks);
foreach ($iterator as $item) {
    // ...
}
```
@Bilge, if you want to contribute to README with an example of usage with Amp or React, feel free to do so. It will be appreciated.
