### ISSUE TITLE
Still Memory Error

### ISSUE THREAD

**Issue by abydahana** [halaxa/json-machine#22]
I tried with 187 Mb of json data and boom! Still get the "Allowed memory size of xxx bytes exhausted (tried to allocate xx bytes)".

**Comment by halaxa** [comment]
-Hi, could you please paste a code  and json snippet which produce this error?

**Comment by abydahana** [comment]
It's too large, buddy. About 187MB (.json file) and i'm sorry can't give it to you because it's contain geometric coordinate for private use. I try many similar library but still not work.

I've solved the problem as i back to the traditional way by exploding the structure and it's kinda faster.

**Comment by halaxa** [comment]
Thats why I said snippet, not the whole thing. Also, data can be anonymized.
Please look at #3, there is probably wrong usage at your side.

**Comment by abydahana** [comment]
Okay please take a look to this snippet (as raw): https://gist.github.com/abydahana/ce2bec53908bc8c181c2ce0d55f11b91

I have "features" object as many as reached to 187MB.

![image](https://user-images.githubusercontent.com/10624446/74212675-ee64ae80-4cc7-11ea-9142-5b6da79c1d36.png)

**Comment by abydahana** [comment]
> Thats why I said snippet, not the whole thing. Also, data can be anonymized.
> Please look at #3, you most likely use it wrong...

No i compared to fewer data and it's work.

**Comment by halaxa** [comment]
Thanks. As I've posted earlier, could you please provide also php code snippet? I cannot point you into right direction without it.

**Comment by halaxa** [comment]
In short, your json pointer should be `"/features"`:
```php
foreach (JsonMachine::fromFile("data.json", "/features") as $feature) {
    var_dump($feature["type"]);
}
```

**Comment by halaxa** [comment]
Is this still relevant @abydahana?

**Comment by halaxa** [comment]
Maybe similar to #24? Closing for now. Feel free to open it again if needed.

**Comment by halaxa** [comment]
Another solution proposed in [Troubleshooting](https://github.com/halaxa/json-machine#troubleshooting).
