### ISSUE TITLE
Memory error too

### ISSUE THREAD

**Issue by Lambik** [halaxa/json-machine#24]
Hi,

I'm sorry for also reporting, but I too get a memory error.

My source file is 5.6 GB, and I've put it up [for download here](http://downloads.compulated.info/tsk/large-json.zip) (the download is 900 MB)

My PHP code is just:

```
<?php

use JsonMachine\JsonMachine;

require('vendor/autoload.php');

$maxlen = [
	'url' => 0,
	'title' => 0,
	'markdownbody' => 0,
];
$counter = 0;
foreach (JsonMachine::fromFile('23-12-2-sites.json') as $item) {
	foreach ($maxlen as $stat => $max) {
		$maxlen[$stat] = max($max, strlen($item[$stat]));
	}
	$counter++;
	echo "item $counter done\n";
}
echo "Found $counter elements\n";
var_dump($maxlen);
```

Error:

```
...
item 3850 done

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 60817416 bytes) in D:\...\vendor\halaxa\json-machine\src\Lexer.php on line 57

Call Stack:
    0.0004     406064   1. {main}() D:\...\script.php:0
  320.8091   23634624   2. JsonMachine\Parser->getIterator() D:\...\script.php:24
  320.8148    8966824   3. JsonMachine\Lexer->getIterator() D:\...\vendor\halaxa\json-machine\src\Parser.php:102

```
The structure is quite simple, it's just an array of basic objects.

It is in theory possible that the json is not valid I suppose, since it's been generated by someone else's script. However, no invalid parsing exception was thrown, possibly because of out-of-memory first.

Could you take a look if I've done something silly? Thanks!

**Comment by Lambik** [comment]
I've tried in a python library, and that took a while on item 3851, but could continue, so it shouldn't be a json error.

**Comment by Lambik** [comment]
Oh. I've isolated the one object in the array, and saved it to a separate file. Which is 70 MB large. So yes, it's not at all an error with your code, but just an actual too large object, so I'll just have to increase my memory settings to handle it.

Sorry for the bother, thanks for the script!

**Comment by halaxa** [comment]
Yes, when a single item in a json is that big, there's no other help then increasing the memory. Another solution might be to use event based stream parser (such as salsify/jsonstreamingparser), which stops at every token, but that is much harder to set up. I'm glad it helped.

**Comment by halaxa** [comment]
Another solution proposed in [Troubleshooting](https://github.com/halaxa/json-machine#troubleshooting).
