### ISSUE TITLE
no download version 5.6(

### ISSUE THREAD

**Issue by yudroma** [halaxa/json-machine#29]
[InvalidArgumentException]
  Package halaxa/json-machine at version  has a PHP requirement incompatible
  with your PHP version (5.3.28)

error composer. Help me please

my version php 5.6.36

**Comment by halaxa** [comment]
Is this message from composer? It says zour PHP version is 5.3.28. Are you sure you're running the version you think you run?

**Comment by yudroma** [comment]
правильно вы говорите 5.3.28 в консоли выдает. А на странице <?php phpinfo()?> выдает PHP Version 5.6.36. Ничего не понимаю(

**Comment by yudroma** [comment]
correctly you say 5.3.28 in the console issues. And on the page <? Php phpinfo ()?> Produces PHP Version 5.6.36. I don’t understand anything (

**Comment by halaxa** [comment]
Your version in console and in web server may differ. Especially if you install PHP manually. I'd suggest to read some tutorial on PHP installation on your platform.

**Comment by yudroma** [comment]
Thank! I will sort this out
