### ISSUE TITLE
how about receiving from http respond as json?

### ISSUE THREAD

**Issue by fgroupindonesia** [halaxa/json-machine#33]
i saw the readme code for 

```
// this often causes Allowed Memory Size Exhausted
- $users = json_decode(file_get_contents('500MB-users.json'));
// this usually takes few kB of memory no matter the file size
+ $users = \JsonMachine\JsonMachine::fromFile('500MB-users.json');
```

But, what if the file is over network? or perhaps call external https / htpp valid json respond...?
Is it applicable or it will be died as well...?

**Comment by halaxa** [comment]
You can use `fromStream` and pass it any stream with JSON response. Even a
strram from network response. There are examples for Guzzle HTTP and
Symfony Http Client in README.

Dne so 7. 11. 2020 5:38 uživatel Gumuruh <notifications@github.com> napsal:

**Comment by halaxa** [comment]
Closing as not an issue. Reply if needed.
