### ISSUE TITLE
Un parse error

### ISSUE THREAD

**Issue by ideea** [halaxa/json-machine#41]
Hello, trying to parse large json file and I have an error. Only first object is parsed and then there's some error.

   $response = JsonMachine::fromFile(storage_path('app/file.json'), '/products', new ErrorWrappingDecoder(new ExtJsonDecoder()));

this is the code I used (also tried with PassThruDecoder) and json_decode by myself, but it does not work cause all items doesn't have { at the beginning.

attaching test json file.

"identifiers": {} ---> this line cause error.

[test.txt](https://github.com/halaxa/json-machine/files/6235973/test.txt)

**Comment by halaxa** [comment]
Thanks, I'm looking into it.

**Comment by halaxa** [comment]
Fixed in #42. Can you check it and continue on the issue there?
