### ISSUE TITLE
error when foreach

### ISSUE THREAD

**Issue by quantrpeter** [halaxa/json-machine#59]
Hi
   if i "$json = JsonMachine::fromFile($_FILES["file"]["tmp_name"]);" a large file and foreach to loop it, it crash

```
foreach ($json as $e) {
    $element = (object)$e;
}
```

If i add "var_dump($element);" inside the foreach loop, it back to work. why?

thanks
Peter

**Comment by halaxa** [comment]
Hi, can you please provide the json structure and the error message? Thanks

**Comment by halaxa** [comment]
Closing for now. Feel free to reopen if the problem persists.
