### ISSUE TITLE
Thank you for this awesome library.

### ISSUE THREAD

**Issue by faizanakram99** [halaxa/json-machine#81]
I want to thank you from core of my heart.

This library is just awesome, especially the ease of using decoders and pointers.

A very big thank you.

**Comment by halaxa** [comment]
Thank you very much. It warms the heart. 🥳

I am glad it's not an Issue 😁

**Comment by faizanakram99** [comment]
I also asked my boss to donate something considering your library was incredibly helpful in dealing with a painfully big json file, I see that he donated 101 $ ... I'm really glad that he did.

**Comment by halaxa** [comment]
I noticed. Thank you very much. It helps to see that it is useful ;)
