### ISSUE TITLE
ER: option or method for preserving the precision of numeric literals

### ISSUE THREAD

**Issue by pkoppstein** [halaxa/json-machine#87]
Currently, the precision of JSON numbers is not, in general, preserved.

Unfortunately, using JSON_BIGINT_AS_STRING, at least by itself, doesn't help, first because it converts all "big integers" to strings (see below), and because it does nothing for "big decimals" (meaning "big or little decimals").

Perhaps asking for the preservation of numeric decimals is too much to ask for in this project; if so,
please interpret this ER as a request for the preservation of integer precision.

--
```
print json_encode(json_decode("[\"123\", 123]", flags: JSON_BIGINT_AS_STRING))."\n";

print json_encode(json_decode("[\"123000000000000000000000000123\", 123000000000000000000000000123]", flags: JSON_BIGINT_AS_STRING))."\n";
```
produces:
```
["123",123]
["123000000000000000000000000123","123000000000000000000000000123"]
```
whereas for the second array, we want:
```
["123000000000000000000000000123",123000000000000000000000000123]
```

**Comment by halaxa** [comment]
Your number will be on most systems bigger than [`PHP_INT_MAX`](https://www.php.net/manual/en/language.types.integer.php), as seen here https://3v4l.org/2HbS6. It means that PHP itself is not able to express that number as a native integer. That's why you get it as a string with `JSON_BIGINT_AS_STRING`. To work wi these 'stringy' integers use [gmp](https://www.php.net/manual/en/book.gmp.php).

**Comment by pkoppstein** [comment]
Perhaps you're saying that this ER is beyond the scope of JSON Machine, but at least for large integers, I think there would be a way if somehow the strings that JSON_BIGINT_AS_STRING creates could be tagged or traced in some manner, so that they can later be printed as though they were integers.  

For example, the strings created by JSON_BIGINT_AS_STRING could be modified to include some bytes that are disallowed in JSON strings, e.g. an initial "\!", so that the PHP string `"\!1"` would finally be rendered as just `1`.

**Comment by halaxa** [comment]
Oh, I see where you're heading. If no decoder is applied, pure source JSON is passed along. See `PassThruDecoder` in README. Just skip decoding entirely and there will be no problems with bigints :)

**Comment by pkoppstein** [comment]
And also skip the final `json_encode`. Yes!!!

**Comment by pkoppstein** [comment]
No decoder, and no json_encode. Yes!!!

Is there any reason why the jm script shouldn't ALWAYS use PassThruDecoder then?

**Comment by pkoppstein** [comment]
The script at https://github.com/halaxa/json-machine/issues/88 using the PassThruDecoder meets my requirements, so I'm closing this issue, even though using that decoder has possibly-unwanted effects.

**Comment by halaxa** [comment]
Sure, no decoding is the best option if you only intend to chunk it.
