### ISSUE TITLE
Basic Usage Using PHP and Brew

### ISSUE THREAD

**Issue by JamesAllgood** [halaxa/json-machine#94]
Hey! 

This is going to be a really basic question, I downloaded the library last week using brew. But having some issues getting it working, never used composer before and when its trying to use the import file command its not working? 

I've used the example but it falls over on trying to use the items::from file command. 

The code looks like this but unsure how to fix it?

use JsonMachine\Items;
use JsonMachine\JsonDecoder\PassThruDecoder;

$users = Items::fromFile

**Comment by halaxa** [comment]
Your snippet doesn't seem complete. Also, usage with PassThruDecoder is described in Readme. Did you check it out?

**Comment by JamesAllgood** [comment]
Here’s the code and the layout of the web repository, the index file is what hosts the code pasted below. 


<?php

//https://github.com/halaxa/json-machine

require __DIR__ . '/vendor/autoload.php';

// $loader = require __DIR__ . '/vendor/autoload.php';
// print_r($loader);

$fruits = Items::fromFile('fruitsArray.json', ['pointer' => '/results/-/color']);

foreach ($fruits as $key => $value) {
    // 1st iteration:
    $key == 'color';
    $value == 'red';
    $fruits->getMatchedJsonPointer() == '/results/-/color';
    $fruits->getCurrentJsonPointer() == '/results/0/color';

    // 2nd iteration:
    $key == 'color';
    $value == 'yellow';
    $fruits->getMatchedJsonPointer() == '/results/-/color';
    $fruits->getCurrentJsonPointer() == '/results/1/color';
}

**Comment by JamesAllgood** [comment]
![67204C38-3B2F-461A-BC44-A052945EB843](https://user-images.githubusercontent.com/10291664/224299291-740a32d0-9c65-41b1-b842-fa1a40cf4048.png)

**Comment by halaxa** [comment]
What error specifically do you get? Can you also provide the contents of fruitsArray.json?

**Comment by halaxa** [comment]
Please provide the requested info in order to keep this issue open.

**Comment by JamesAllgood** [comment]
> What error specifically do you get? Can you also provide the contents of fruitsArray.json?

This is the location of the code. 

http://test.themeparkguide.co.uk
http://test.themeparkguide.co.uk/fruitsArray.json

index.php code is...
`<H1>Testing Code</H1>

<?php

//https://github.com/halaxa/json-machine

use \JsonMachine\Items;

$fruits = Items::fromFile('fruits.json', [
    'pointer' => ['/berries', '/citruses']
]);

foreach ($fruits as $key => $value) {
    // 1st iteration:
    $value == ["name" => "strawberry", "color" => "red"];
    $fruits->getCurrentJsonPointer() == '/berries';

    // 2nd iteration:
    $value == ["name" => "raspberry", "color" => "red"];
    $fruits->getCurrentJsonPointer() == '/berries';

    // 3rd iteration:
    $value == ["name" => "orange", "color" => "orange"];
    $fruits->getCurrentJsonPointer() == '/citruses';

    // 4th iteration:
    $value == ["name" => "lime", "color" => "green"];
    $fruits->getCurrentJsonPointer() == '/citruses';
}

?>`

**Comment by halaxa** [comment]
What you expect this code to do exactly?
